//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Table
    {
        public string Cust_ID { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public long mobile { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string address { get; set; }
    }
}
