//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Table
    {
        public string Order_ID { get; set; }
        public string Cust_ID { get; set; }
        public string Product_ID { get; set; }
        public int quantity { get; set; }
        public decimal total_price { get; set; }
        public string Transaction_ID { get; set; }
    }
}
