//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Table
    {
        public string id { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public double price { get; set; }
        public double rating { get; set; }
        public string company_name { get; set; }
        public string category { get; set; }
        public int quantity { get; set; }
        public string img { get; set; }
        public System.DateTime date { get; set; }
        public bool delivery { get; set; }
    }
}
